version: '3.8'

services:
  murmur:
    image: goofball222/murmur
    ports:
      - 64738:64738
      - 64738:64738/udp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - type: bind
        source: /etc/letsencrypt
        target: /opt/murmur/cert
        read_only: true
      - ./config:/opt/murmur/config
      - ./data:/opt/murmur/data
      # - ./log:/opt/murmur/log
    environment:
      - TZ=UTC
