version: '3.8'

services:
  murmur:
    image: goofball222/murmur
    ports:
      - 64738:64738
      - 64738:64738/udp
    volumes:
      # - ./log:/opt/murmur/log
      - ./config:/opt/murmur/config
      - ./data:/opt/murmur/data
      - /etc/letsencrypt:/opt/murmur/cert
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
    environment:
      - TZ=UTC
